version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "22.16.0"
  resource-class:
    type: string
    default: "small"
  yarn-version:
    type: string
    default: "4.2.2"

orbs:
  coveralls: coveralls/coveralls@2.2.1

commands:
  install-yarn:
    description: "Install Yarn"
    steps:
      - run: corepack enable --install-directory ~/bin
      - run: yarn set version << pipeline.parameters.yarn-version >>
  install-dependencies:
    description: "Install Dependencies"
    steps:
      - run: yarn install

jobs:
  coverage:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run Code Coverage
          command: yarn coverage
      - run:
          name: Generate Code Coverage lcov File
          command: yarn run nyc --reporter=text-lcov report > coverage.lcov
      - coveralls/upload:
          coverage_file: coverage.lcov
  lint:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Lint
          command: yarn lint

  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Build
          command: yarn build

  run-example:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run Example
          command: yarn example

workflows:
  build-and-test:
    jobs:
      - lint
      - build
      - coverage
      - run-example
